# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180416_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='ownedr_id',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='applets',
            old_name='ownedr_id',
            new_name='owner_id',
        ),
    ]
